### ISSUE TITLE
can you give a upload sample write in swift

### ISSUE THREAD

**Issue by blesshappy** [frederik-jacques/TNSexyImageUploadProgress#2]
your code is very useful for me,but i m the newer for ios develop.
i writting code in xcode6-beta6 in swift,could you give me a sample?
another,your sample server program are php,i use the java server:tomcat,could you give a test webservice url?
thks a lot!

**Comment by frederik-jacques** [comment]
Sorry, I'm not familiar with Tomcat.  The webservice part is also not important to make the code work, as long as your webservice returns the amount of bytesLoaded all should just work fine :)
